#!/bin/sh
#
wget -N --no-check-certificate https://github.com/afdbdmn/openwrt/raw/main/Pi3Wrt/xderm-mini/badvpn_1.999.130-1_aarch64_cortex-a53.ipk https://github.com/afdbdmn/openwrt/raw/main/Pi3Wrt/xderm-mini/corkscrew_2.0-1_aarch64_cortex-a53.ipk https://github.com/blackstar-git/openwrt/raw/main/Pi3Wrt/xderm-mini/v2ray-core_4.34.0-1_aarch64_cortex-a53.ipk -P /root/temporary/
opkg update && opkg install --force-depends /root/temporary/*.ipk && rm -R temporary
opkg remove dnsmasq && opkg install dnsmasq-full
/etc/init.d/dnsmasq restart
/etc/init.d/network restart
clear
